##########################
#### ElytraCombatFix #####
##########################

# Permissions:

# Commands:

##########################
##### Configuration  #####
##########################

# Amount of seconds that the elytra will be removed.
time: 5

show-actionbar-message: true

message-seized: "&cYour elytra has been seized for {time} seconds!"
message-returned: "&aYour elytra has been returned!"

# You can set what damage types trigger the removal of the elytra.
damage-types:
  BLOCK_EXPLOSION: true
  CONTACT: false
  CRAMMING: false
  CUSTOM: true
  DRAGON_BREATH: true
  DROWNING: false
  DRYOUT: true
  ENTITY_ATTACK: true
  ENTITY_EXPLOSION: true
  ENTITY_SWEEP_ATTACK: true
  FALL: false
  FALLING_BLOCK: false
  FIRE: false
  FIRE_TICK: false
  FLY_INTO_WALL: true
  HOT_FLOOR: false
  LAVA: false
  LIGHTNING: true
  MAGIC: true
  MELTING: true
  POISON: true
  PROJECTILE: true
  STARVATION: false
  SUFFOCATION: false
  SUICIDE: false
  THORNS: true
  VOID: true
  WITHER: true


##########################
##### Update Checker #####
##########################

# Checks for updates (asynchronously).
# When enabled, a message is printed in the console if a new
# version has been found, and OPs will be notified when they join the server
# When set to true, check for updates on startup and every X hours (see below)
# When set to on-startup, only check on server startup
# When set to false, don't check for updates
check-for-updates: true

# When you set "check-for-updates" to true, you can define the amount
# of hours between each update check.
update-check-interval: 4